logging:
  file: flow.log
 
cx-flow:
  contact: william.berriel@checkmarx.com

  bug-tracker-impl:
    - CxXml
    - Csv
    - Json
    - GitLab
    - GitHub
    - Azure
    - Rally
  branches:
    - develop
    - master
    - release`-\w+ # regular expressions supported. If branch-script is provided, this is ignored. branch-script: D:\\tmp\Branch.groovy #default empty/not used
  filter-severity:
    - High

  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  wiki-url: https://checkmarx.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://cxa.codebashing.com/courses/
  track-application-only: false
  web-hook-queue: 20
  scan-result-queue: 4
  break-build: false
  scan-resubmit: false
  http-connection-timeout: 3000 #milliseconds - default 30000
  http-read-timeout: 120000 #milliseconds - default 120000
  enabled-vulnerability-scanners:
    - sast
    - SCA

checkmarx:
  version: 9.0
  scope: access_control_api sast_rest_api
  client-id: resource_owner_client
  multi-tenant: false
  scan-preset: Checkmarx DefaulPlus
  configuration: Default Configuration
  team: /CxServer/CxFlow
  scan-timeout: 120 #Webhook and --scan command line only, number of minutes
  url: ${checkmarx.base-url}/cxrestapi
#WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
#  project-script: D:\\tmp\CxProject.groovy #default empty/not used
#  team-script: D:\\tmp\CxTeam.groovy #default empty/not used


 

json:
  data-folder: ""
  file-name-format: "Checkmarx-[TIME].json"
 
cx-xml:
  file-name-format: "[NAMESPACE]-[REPO]-[BRANCH]-[TIME].xml"
  data-folder: "C:\\tmp"

